"""Defines a function that takes a set of quadratic fit coefficients and a range of x values, and generates an array
representing the coordinates of the fit curve over that interval"""

__author__ = "Tyler Gurney"

import sys
from numpy import *


def fit_curve_array(quadratic_coefficients, minimum_x, maximum_x, number_of_points = 100):
    """Takes as input:
    quadratic_coefficients: list of coefficients,
    ordered [constant_coefficient, linear_coefficient, quadratic_coefficient] (can use calculate_quadratic_fit to generate)
    minimum_x: float/int value representing minimum x value of range of points to be calculated for curve
    maximum_x: float/int value representing maximum x value of range of points to be calculated for curve
    number of points: determines how many points are created for storage in output array, default value is 100

    Function Returns fit_curve array, which consists of the x values generated by linspace, and the matching y values"""
    try:
        constant_term = quadratic_coefficients[0]
        linear_term = quadratic_coefficients[1]
        quadratic_term = quadratic_coefficients[2]
        x_values = linspace(minimum_x, maximum_x, number_of_points)
        y_values = constant_term + linear_term*x_values + quadratic_term*(x_values**2)
        fit_curve = [x_values, y_values]
    except IndexError:
        print("Not enough points in input parameters, please ensure quadratic_coefficients is a 3x1 array"
              "\nand that number_of_points > 2")
        sys.exit(1)
    except ArithmeticError:
        print("maximum_x < minimum_x, please retry with valid input parameters")
        sys.exit(1)
    return fit_curve


if __name__ == "__main__":
    test_coefficients = [0, 0, 1]
    print(f"Point Arrays generated by fit_curve_array for:"
          f"\nquadratic_coefficients = {test_coefficients} with minimum_x = -2 and maximum_x = 2")
    print(fit_curve_array([0, 0, 1], -2, 2))
    print("\n\n")
    test_x_values = linspace(-2,2,100)
    test_y_values = test_x_values**2
    test_comparison = [test_x_values, test_y_values]
    print("Point arrays generated by squaring linspace array over same interval, representing y = x**2\n")
    print(test_comparison)
