"""Module defines a function plot_data_with_fit that takes data points and fit curve from fit_curve_array and
simultaneously plots the scatter plot of data points and the corresponding curve of best fit"""

__author__ = "Tyler Gurney"

import matplotlib.pyplot as plt
from numpy import linspace
import sys


def plot_data_with_fit(data, fit_curve, data_format='o', fit_format=""):
    """Takes as input:
    data: (2,M) dimensional array representing (x,y) coordinates for scatter plot data
    fit_curve: array generated by fit_curve_array function that represents points on curve of best fit
    data_format: represents format for scatter plot points, default value 'o' (see matplotlib documentation for options)
    fit_format: represents format for fit curve, default value left blank (see matplotlib documentation for options)

    Function returns combined_plot, which is a plot generated via matplotlib.pyplot that has both
    the scatter plot points and best fit curve on the same graph"""
    try:
        data_x_values = data[0]
        data_y_values = data[1]
        curve_x_values = fit_curve[0]
        curve_y_values = fit_curve[1]
        combined_plot = plt.plot(data_x_values, data_y_values, data_format, curve_x_values, curve_y_values, fit_format)
    except IndexError:
        print("Please make sure data and fit_curve inputs are 2xM dimensional arrays")
        sys.exit(1)
    return combined_plot


if __name__ == "__main__":
    test_data = [[-2, -1, 0, 1, 2], [4, 1, 0, 1, 4]]
    test_fit_curve = [linspace(-2, 2), linspace(-2,2)**2]
    plot_data_with_fit(test_data, test_fit_curve, data_format="x",  fit_format="--")
    plt.show()
